name: My first GH Actions workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: My hello world
        run: echo "Hello World"
      - name: multiple commands
        run: |
          git -v
          whoami
          echo "bye"
      - name: which area are we running
        run: |
          ls
          pwd
      - name: Checkout command checking
        uses: actions/checkout@v1